version: "3.9"

services:
  campaigngenie:
    build: .
    container_name: campaigngenie
    env_file: # keeps secrets out of git
      - .env
    ports:
      - "8501:8501"         # host:container
    volumes:
      # optional: persist uploads / generated DBs between runs
      - campaigngenie_data:/app/pages/files
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: campaign_genie
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  campaigngenie_data:
  mongodb_data:
